### ISSUE TITLE
scp-ing a file on the fly?!

### ISSUE THREAD

**Issue by jack-h** [HERA-Team/paper_gpu#30]
https://github.com/HERA-Team/paper_gpu/blob/952df0e19828e2970f23b5b30b22d176cf641b70/src/scripts/hera_catcher_up.py#L79

This is crazy, even by `paper_gpu` standards.

The bda config should probably just come through the redis->shared memory gateways. Unlike the hdf5 template, it never has to be an actual file.

**Comment by mkolopanis** [comment]
A stale bda_config caused some weird issues today and this came back up. @AaronParsons suggest we just use redis to store the bda config.
