### ISSUE TITLE
Array longitude set to latitude 

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/paper_gpu#33]
The longitude of the array seems to be being set to the latitude of the array.

https://github.com/HERA-Team/paper_gpu/blob/2d2fa57e8fa6f36991831cee05100d4cc5ec89bb/src/scripts/hera_make_hdf5_template_bda.py#L169

**Comment by jack-h** [comment]
Merged in PR #34 .
Should take effect at next restart.
